module(name = "using_portable_python")
bazel_version = "8.4.2"

## For using a portable Python distro
# Example use: bazel run @portable_python//:python -- -m pydoc math
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "portable_python",
    urls = ["https://github.com/qznc/portable_python/releases/download/v0.4.1/python-3.12.12-x86_64-linux.tar.gz"],
    sha256 = "492b13eadd3c48c8113df98f81275697d60711d7c2f74e9dbbe5287013cb1b00",
    strip_prefix = "python",
    build_file_content = """
sh_binary(
    name = "python",
    srcs = ["bin/python3"],
    data = glob(["**"]),
    visibility = ["//visibility:public"],
)
""",
)
