module(name = "using_portable_python")
bazel_version = "8.4.2"

## For using a portable Python distro
# Example use: bazel run @portable_python//:python -- -m pydoc math
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "portable_python",
    urls = ["https://github.com/qznc/portable_python/releases/download/v0.4.1/python-3.12.12-x86_64-linux.tar.gz"],
    sha256 = "ed783d559806275a7e3bae4034e1ff867c43dc09932add23aeca7595f05f6c1b",
    strip_prefix = "python",
    build_file_content = """
sh_binary(
    name = "python",
    srcs = ["bin/python3"],
    data = glob(["**"]),
    visibility = ["//visibility:public"],
)
""",
)
